ame: CI
on: [push]
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.7"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: flake8 linting
        run: poetry run flake8 .
      - name: black code formatting
        run: poetry run black . --check
      - name: pytest
        run: poetry run pytest
